#####
# This file is part of the MediaWiki extension Esv.
#
# MIT License
#
# Copyright (c) 2015-2020 Kungfubonanza
#        
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#                               
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#                                
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE. 
#
# @author Kungfubonanza
# @file
# @ingroup Esv
#####

language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=master; GROUP=extensions-esv
      php: 7.0
    - env: DBTYPE=mysql; MW=1.30.0; GROUP=extensions-esv
      php: 7.2
    - env: DBTYPE=mysql; MW=1.28.0; GROUP=extensions-esv-unit
      php: 5.6
    - env: DBTYPE=postgres; MW=1.27.0; GROUP=extensions-esv-unit
      php: 5.5

script:
    - bash ./build/travis/script.sh
